#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run commitizen hook only when installed locally.
if [ -x "./node_modules/.bin/cz" ]; then
	exec < /dev/tty && ./node_modules/.bin/cz --hook || true
fi
